version: '3.8'

name: forum_project

services:
  web:
    container_name: forum_web
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: forum_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=diamond_tofu_user
      - POSTGRES_PASSWORD=diamond_tofu_password
      - POSTGRES_DB=diamond_tofu

volumes:
  postgres_data: