# Generated by Django 4.1.2 on 2023-03-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='interest',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='thread',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
